[archive]
build_output_dir = 'Built'
archive_location = '\\us-aus-hilbuild\builds\niveristandadd-ons\libraries\advanced_sys_def'

[package]
type = 'viPackage'
vipb_path = 'Advanced SysDef API.vipb'
output_path = 'Built'
